### ISSUE TITLE
贴图丢失

### ISSUE THREAD

**Issue by LuckyBYR** [ima-games/ATD#1]
我想问一下您，为什么用unity打开后贴图都是粉色的吗，怎么解决这个问题，挺急的，谢谢！

**Comment by KillerAery** [comment]
![image](https://user-images.githubusercontent.com/31158107/67101285-ea31f400-f1f3-11e9-8998-a214772f4fdd.png)

![Unity_qtUZdb0Zj9](https://user-images.githubusercontent.com/31158107/67103743-4d258a00-f1f8-11e9-91ed-c842fdf1d937.png)

![adHRPYXYJy](https://user-images.githubusercontent.com/31158107/67103729-472fa900-f1f8-11e9-9786-58f799483ad6.png)

需要shadergraph,post processing

**Comment by LuckyBYR** [comment]
![fca240deb28a8e7c97f3c0daa66f545](https://user-images.githubusercontent.com/51043111/67105284-12712100-f1fb-11e9-9bf4-f9788eac8b57.png)
我按照您说的安装上了，但还是不行，是不是materials里面东西出问题了呀

**Comment by LuckyBYR** [comment]
![图片](https://user-images.githubusercontent.com/51043111/67106063-82cc7200-f1fc-11e9-98c4-7ed3226bcc62.png)
![图片](https://user-images.githubusercontent.com/51043111/67106076-8b24ad00-f1fc-11e9-90bc-d2ca7993a573.png)
按照您说的办法还是不行，后面那些房子、树什么的是在Asset Store里面找到的，但一些塔、怪物、和英雄之类的还是粉色的。

**Comment by KillerAery** [comment]
因为项目配置了LWRP的原因，package还有一个LightWeight RP，不过要注意它依赖的其他package是否满足条件

![image](https://user-images.githubusercontent.com/31158107/67136389-167f5c00-f258-11e9-8296-30e14c2d626f.png)

装完package后，可能材质会被更改成默认值（变成灰色），
在文件夹看到材质显示成粉色，目前的临时解决方法是：
1. 一个个材质都点一下，然后它就会恢复成默认的灰色材质。
2. 关掉Unity（为了让它更新材质文件）
3. 在git记录会发现材质文件被修改，此时得手动在git撤销对材质文件的更改。
4. 打开Unity，就能正常看到项目了。

**Comment by LuckyBYR** [comment]
![图片](https://user-images.githubusercontent.com/51043111/67143146-f02ee000-f29a-11e9-9663-7f33dfa6f5a1.png)
还有一点小问题  有几个塔的模型出不来.........
血条和技能栏也不知道去哪了

**Comment by KillerAery** [comment]
塔的模型有几个材质错误了，之后我找个时间修复一下。
UI显示不全是项目固定1920*1600分辨率下开发，可以调一下，不要用FreeAspect。

**Comment by LuckyBYR** [comment]
好的，这几天麻烦您了！因为我之前从来没有接触过unity和C#所以就很多东西不知道，问了一些挺脑残的问题......

**Comment by KillerAery** [comment]
已更新。
